name: flutter_native_ui_cross_example
description: An example project for https://betterprojectsfaster.com/guide/getting-started-flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_platform_widgets: 2.0.0
  macos_ui: 1.7.5
  fluent_ui: 4.0.3+1
  font_awesome_flutter: 10.2.1
  window_manager: 0.2.7
  url_launcher: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
