name: flutter_native_ui_cross_example
description: An example project for https://betterprojectsfaster.com/guide/getting-started-flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  flutter_platform_widgets: 3.3.5
  macos_ui:
    git:
      url: https://github.com/macosui/macos_ui
      ref: f1053fc31958dbaa362a0a4c8288e8cf0919ab8c

  fluent_ui: 4.6.2
  font_awesome_flutter: 10.4.0
  window_manager: 0.3.4
  url_launcher: 6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
